# -*- coding: utf-8 -*-
"""ChatBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jw94PDicfBq3xqC_26eQ-C6UdGFFLDHI
"""

pip install chatterbot

!pip install chatterbot_corpus

from chatterbot import ChatBot

bot = ChatBot(
    'Uj',  
    logic_adapters=[
        'chatterbot.logic.BestMatch',
        'chatterbot.logic.TimeLogicAdapter'],
)

from chatterbot.trainers import ChatterBotCorpusTrainer

trainer = ChatterBotCorpusTrainer(bot)

trainer.train('chatterbot.corpus.english')

name=input("Enter Your Name: ")
print("Hi "+name+", how can I help you?")
while True:
    request=input(name+':')
    if request=='Bye' or request =='bye':
        print('Uj: Bye')
        break
    else:
        response=bot.get_response(request)
        # get_reponses() is a method of chatbot instance
        print('Uj:',response)